OLED_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
WPM_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_MAP_ENABLE = yes

#Debug options
VERBOSE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

LTO_ENABLE = yes
SPLIT_KEYBOARD = yes
VIA_ENABLE = yes