OLED_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = yes
SPLIT_KEYBOARD = yes
WPM_ENABLE = yes

# CONSOLE_ENABLE = yes
# ENCODER_ENABLE = yes
# EXTRAKEY_ENABLE = yes
# OLED_ENABLE = yes
# VIA_ENABLE = yes
# LTO_ENABLE = yes
# WPM_ENABLE = yes
# SPLIT_KEYBOARD = yes